### ISSUE TITLE
Integration in NextJS

### ISSUE THREAD

**Issue by iamgenchi** [torusresearch/torus-direct-web-sdk#100]
Hi @chaitanyapotti,

I have built an example for NextJS - works perfectly:

https://github.com/cittizen/nextjs-torus-direct-web-sdk

Do you want to integrate it in your `/examples`?

**Comment by chaitanyapotti** [comment]
Yes. Please submit a PR and we would be happy to integrate

**Comment by iamgenchi** [comment]
@chaitanyapotti Fantastic - here it is!

https://github.com/torusresearch/torus-direct-web-sdk/pull/101

**Comment by chaitanyapotti** [comment]
Closing this
