### ISSUE TITLE
To reduce logo size for email password

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-direct-web-sdk#30]
The current logo for email password login is too large. Please reduce it to 128px (reference to the second pic attached) <img width="540" alt="Screenshot 2020-06-15 at 1 44 51 PM" src="https://user-images.githubusercontent.com/53069682/84622076-c81d7c80-af0e-11ea-8cf5-f75502973995.png">
<img width="413" alt="Screenshot 2020-06-15 at 1 46 52 PM" src="https://user-images.githubusercontent.com/53069682/84622148-df5c6a00-af0e-11ea-99bc-e1abbf8bc30b.png">

**Comment by chaitanyapotti** [comment]
Not here please
