### ISSUE TITLE
Torus w/ Express

### ISSUE THREAD

**Issue by cawfree** [torusresearch/torus-direct-web-sdk#43]
Thanks very much for your awesome work! 🤝 

I've published this [repo](https://github.com/cawfree/express-torus) to use [Tor.us](https://tor.us/) as a drop-in [express](https://github.com/expressjs/express) middleware. I've reused the API keys that were specified in your Vue example; I hope that's okay! 🚀

**Comment by tetratorus** [comment]
Yes, it's okay, awesome work btw :+1:
