### ISSUE TITLE
Unable to use own credentials for passwordless login with Auth0 in example

### ISSUE THREAD

**Issue by JasoonS** [torusresearch/torus-direct-web-sdk#49]
I have been been unable to get email passwordless login working with Auth0 both in the vue example included in this repo and in my own code.

Steps to reproduce the passwordless login issue with Auth0:

1. Create an account with Auth0.
2. Create a new application.
3. Enable passwordless email. Use the default settings.
![](https://i.imgur.com/BeiW1Rt.png)
4. Go to the settings of your application and make sure the following settings are correct:
![](https://i.imgur.com/mTkNxGv.png)
![](https://i.imgur.com/dqk3w8U.png)
5. Enable passwordless login, disable other options:
![](https://i.imgur.com/AlFdLfx.png)
6. Add the client ID and login domain to the login config of torus(for example in the vue example):
![](https://i.imgur.com/VNVkEcY.png)
7. Attempt a passwordless login, and you will be met with the following page and console error:
![](https://i.imgur.com/50PyjwG.png)
![](https://i.imgur.com/NoU1hwA.png)

I am aware that this is more likely to be an issue on Auth0's side, however I would appreciate if you looked at my steps to reproduce and could tell me how your configuration is different. I'm sure I won't be the only one to bump into this issue, and followed the instructions from Auth0 to the letter.

Thank you for you help

**Comment by chaitanyapotti** [comment]
Please use passwordless Lock template for Universal login as shown in the image

![image](https://user-images.githubusercontent.com/1688380/90245923-265ed100-de66-11ea-9e2f-f7ca4f2ad162.png)
