### ISSUE TITLE
Internal error "code":-32602

### ISSUE THREAD

**Issue by MrHOY** [torusresearch/torus-direct-web-sdk#53]
I try to clone and run angular-app in examples folder, replace with my Google clientID but it return error

Error: Unable to resolve enough promises, errors: [null,null,null,null,null], responses: [{"jsonrpc":"2.0","error":{"code":-32602,"message":"Internal error","data":"Error occurred while verifying paramsazip is not clientID 75612027790-g73324pote4ojfmra3gfecsnr5i9bk61.apps.googleusercontent.com 366106252773-1kiihfdl71bu24ahb0hogtapdnfm2984.apps.googleusercontent.com"},"id":10},{"jsonrpc":"2.0","error":{"code":-32602,"message":"Internal error","data":"Error occurred while verifying paramsazip is not clientID 75612027790-g73324pote4ojfmra3gfecsnr5i9bk61.apps.googleusercontent.com 366106252773-1kiihfdl71bu24ahb0hogtapdnfm2984.apps.googleusercontent.com"},"id":10},{"jsonrpc":"2.0","error":{"code":-32602,"message":"Internal error","data":"Error occurred while verifying paramsazip is not clientID 75612027790-g73324pote4ojfmra3gfecsnr5i9bk61.apps.googleusercontent.com 366106252773-1kiihfdl71bu24ahb0hogtapdnfm2984.apps.googleusercontent.com"},"id":10},{"jsonrpc":"2.0","error":{"code":-32602,"message":"Internal error","data":"Error occurred while verifying paramsazip is not clientID 75612027790-g73324pote4ojfmra3gfecsnr5i9bk61.apps.googleusercontent.com 366106252773-1kiihfdl71bu24ahb0hogtapdnfm2984.apps.googleusercontent.com"},"id":10},{"jsonrpc":"2.0","error":{"code":-32602,"message":"Internal error","data":"Error occurred while verifying paramsazip is not clientID 75612027790-g73324pote4ojfmra3gfecsnr5i9bk61.apps.googleusercontent.com 366106252773-1kiihfdl71bu24ahb0hogtapdnfm2984.apps.googleusercontent.com"},"id":10}], predicate: invalid

![image](https://user-images.githubusercontent.com/20653706/93860419-49906200-fce9-11ea-9ab3-3a195168587c.png)

**Comment by chaitanyapotti** [comment]
Hey, that's because you need to get a new verifier deployed to match your client id.
please reach out to hello@tor.us or join our [telegram developer group](https://t.me/torusdev)
