### ISSUE TITLE
Documentation - LRC Environment

### ISSUE THREAD

**Issue by iamgenchi** [torusresearch/torus-direct-web-sdk#92]
Hi Team,

Noticed you have an LRC environment `https://lrc.tor.us`.

What is [that](https://github.com/torusresearch/torus-website/blob/develop/.env.lrc) environment and who can use it?

It's not documented as far as I could tell, though the implementation [documentation](https://docs.tor.us/integration-builder/?b=customauth&chain=Ethereum&lang=React) is using it:

```
const verifierMap = {
  [GOOGLE]: {
    //...
    verifier: "google-lrc",
  },
```

It seems to be on Ropsten, what does LRC mean?

**Comment by chaitanyapotti** [comment]
LRC means "long running cluster"
It's an internal representation of torus testnet cluster.

In this sdk, if you use `network: "testnet"`, you will be using lrc nodes of torus network.
